id: queen-server-id
subscription_quota_enabled: false
jobs:
  launch_topic_suffix: -anon-local
db:
  encryption_key: my-db-key
  db_type: sqlite
  data_source: formicary_db.sqlite
common:
  development: true
  user_agent: ""
  proxy_url: ""
  public_dir: "./public/"
  messaging_provider: REDIS_MESSAGING
  xmessaging_provider: KAFKA_MESSAGING
  http_port: 0
  external_base_url: http://localhost:7777
  auth:
    enabled: false
    jwt_secret: changeme
  xmonitoring_urls:
    docker: "localhost:2375"
  disabled_pulsar:
    url: "pulsar://localhost:6650"
    connection_timeout: 30
  kafka:
    brokers:
      - 192.168.1.102:19092
      - 192.168.1.102:29092
    group: formicary-queen-1
  redis:
    host: "192.168.1.102"
    port: 6379
  s3:
    endpoint: "192.168.1.102:9000"
    accessKeyID: "admin"
    secretAccessKey: "password"
    region: "us-west-2"
    bucket: "formicary-artifacts"
    prefix: "formicary/"
smtp:
    from_email: "support@formicary.io"
    provider: ""
    api_key: ""
    username: ""
    password: ""
    host: ""
    port: 0
notify:
    email_jobs_template_file: views/notify/email_notify_job.html
    slack_jobs_template_file: views/notify/slack_notify_job.txt
    verify_email_template_file: views/notify/verify_email.html
    user_invitation_template_file: views/notify/user_invitation.html
