methods:
  - DOCKER
  - KUBERNETES
  - SHELL
  - HTTP_GET
  - HTTP_POST_FORM
  - HTTP_POST_JSON
  - HTTP_PUT_FORM
  - HTTP_PUT_JSON
  - HTTP_DELETE
docker:
  host: "tcp://192.168.1.100:2375"
kube: "https://localhost:55000"
common:
  id: ant-worker-id
  user_agent: "formicary-agent"
  development: true
  public_dir: "./public/"
  proxy_url: ""
  messaging_provider: REDIS_MESSAGING
  xmessaging_provider: KAFKA_MESSAGING
  max_job_timeout: 0s
  max_task_timeout: 0s
  http_port: 0
  xmonitoring_urls:
    docker: "localhost:2375"
  disabled_pulsar:
    url: "pulsar://localhost:6650"
    connection_timeout: 30
  kafka:
    brokers:
      - 192.168.1.102:19092
      - 192.168.1.102:29092
      - 192.168.1.102:39092
    group: formicary-ant-1
  redis:
    host: "192.168.1.102"
    port: 6379
    password: ""
    ttl_minutes: 0s
    pool_size: 0
    max_subscription_wait: 0s
  s3:
    endpoint: "192.168.1.102:9000"
    accessKeyID: "admin"
    secretAccessKey: "password"
    region: "us-west-2"
    bucket: "formicary-artifacts"
    prefix: "formicary/"
    encryptionPassword: ""
    useSSL: false
  auth:
    enabled: false
kubernetes:
  allow_privilege_escalation: true
  pod_security_context:
    run_as_user: 0
